# Generated by Django 4.1 on 2022-08-22 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220812_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 11, 16, 1, 955106, tzinfo=datetime.timezone.utc)),
        ),
    ]
